version: '3'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  newman:

services:

  volume:
    image: docker.iotechsys.com/edgexpert/docker-edgex-volume-${EX_ARCH}:${EX_VER}
#    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  consul:
    image: docker.iotechsys.com/services/consul-${EX_ARCH}:1.2.2
#    ports:
#      - "8400:8400"
#      - "8500:8500"
#      - "8600:8600"
#    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  config-seed:
    image: docker.iotechsys.com/edgexpert/config-seed-go-${EX_ARCH}:${EX_VER}
#    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
            - edgex-core-config-seed
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - consul

  mongo:
    image: docker.iotechsys.com/edgexpert/docker-edgex-mongo-${EX_ARCH}:1.1.0
#    ports:
#      - "27017:27017"
#    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      edgex-network:
        aliases:
            - edgex-mongo
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - newman:/etc/newman
    depends_on:
      - volume

  redis:
    image: redis:5
    ports:
    - "6379:6379"
    container_name: edgex-redis
    hostname: edgex-redis
    networks:
      edgex-network:
        aliases:
        - edgex-redis
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  logging:
    image: docker.iotechsys.com/edgexpert/support-logging-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /support-logging
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48061:48061"
#    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      edgex-network:
        aliases:
          - edgex-support-logging
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - redis
      - volume

  notifications:
    image: docker.iotechsys.com/edgexpert/support-notifications-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /support-notifications
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48060:48060"
#    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      edgex-network:
        aliases:
          - edgex-support-notifications
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - logging

  metadata:
    image: docker.iotechsys.com/edgexpert/core-metadata-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /core-metadata
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48081:48081"
#    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      edgex-network:
        aliases:
          - edgex-core-metadata
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses

  data:
    image: docker.iotechsys.com/edgexpert/core-data-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /core-data
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48080:48080"
#      - "5563:5563"
#    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      edgex-network:
        aliases:
          - edgex-core-data
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses

  command:
    image: docker.iotechsys.com/edgexpert/core-command-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /core-command
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48082:48082"
#    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      edgex-network:
        aliases:
          - edgex-core-command
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - metadata

  scheduler:
    image: docker.iotechsys.com/edgexpert/support-scheduler-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /support-scheduler
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48085:48085"
#    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      edgex-network:
        aliases:
          - edgex-support-scheduler
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - metadata

  export-client:
    image: docker.iotechsys.com/edgexpert/export-client-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /export-client
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48071:48071"
#    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      edgex-network:
        aliases:
          - edgex-export-client
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - data
    environment:
      - EXPORT_CLIENT_MONGO_URL=edgex-mongo
      - EXPORT_CLIENT_DISTRO_HOST=edgex-export-distro
      - EXPORT_CLIENT_CONSUL_HOST=edgex-core-consul

  export-distro:
    image: docker.iotechsys.com/edgexpert/export-distro-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /export-distro
      - --consul=${EX_CONSUL}
      - --profile=docker
      - --confdir=/res
#    ports:
#      - "48070:48070"
#    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      edgex-network:
        aliases:
          - edgex-export-distro
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - export-client
    environment:
      - EXPORT_DISTRO_CLIENT_HOST=edgex-export-client
      - EXPORT_DISTRO_DATA_HOST=edgex-core-data
      - EXPORT_DISTRO_CONSUL_HOST=edgex-core-consul
      - EXPORT_DISTRO_MQTTS_CERT_FILE=none
      - EXPORT_DISTRO_MQTTS_KEY_FILE=none


#  rulesengine:
#    image: docker.iotechsys.com/edgexpert/support-rulesengine-java-${EX_ARCH}:${EX_VER}
#    ports:
#      - "48075:48075"
#    container_name: edgex-support-rulesengine
#    hostname: edgex-support-rulesengine
#    networks:
#      edgex-network:
#        aliases:
#          - edgex-support-rulesengine
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
#    depends_on:
#      - export-distro

  postman:
    image: docker.iotechsys.com/services/newman_${EX_ARCH}:4.0.2
    networks:
      edgex-network:
        aliases:
          - postman
    volumes:
      - newman:/etc/newman

#################################################################
# Management Console
#################################################################

  iotech-manager:
    image: docker.iotechsys.com/edgexpert/iotech-manager-${EX_ARCH}:${EX_VER}
    ports:
      - "8080:8080"
    container_name: iotech-manager
    hostname: iotech-manager
    networks:
      - edgex-network
    depends_on:
      - volume
      - metadata
      - data
      - command

#################################################################
# Device Services
#################################################################

#  device-virtual:
#    image: docker.iotechsys.com/edgexpert/device-virtual-java-${EX_ARCH}:${EX_VER}
#    entrypoint:
#      - java
#      - -jar
#      - -Djava.security.egd=file:/dev/urandom
#      - -Xmx100M
#      - device-virtual.jar
#      - --spring.cloud.consul.enabled=${EX_CONSUL}
#      - --logging.remote.enable=${EX_LOG}
#    ports:
#      - "49990:49990"
#    container_name: edgex-device-virtual
#    hostname: edgex-device-virtual
#    networks:
#      - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
#    depends_on:
#      - data
#      - command

#  device-sdk:
#    image: docker.iotechsys.com/edgexpert/device-sdk-java-${EX_ARCH}:${EX_VER}
#    entrypoint:
#      - java
#      - -jar
#      - -Djava.security.egd=file:/dev/urandom
#      - -Xmx100M
#      - device-sdk.jar
#      - --spring.cloud.consul.enabled=${EX_CONSUL}
#      - --logging.remote.enable=${EX_LOG}
#    ports:
#      - "49999:49999"
#    container_name: edgex-device-sdk
#    hostname: edgex-device-sdk
#    networks:
#      edgex-network:
#        aliases:
#          - edgex-device-sdk
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
#    depends_on:
#      - data
#      - command

  device-opc-ua:
    image: docker.iotechsys.com/edgexpert/device-opc-ua-c-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /device_opcua
      - --confdir=/res
      - --name=device-opcua
      - --registry=${EX_CONSUL}
    ports:
      - "49952:49952"
    container_name: edgex-device-opc-ua
    hostname: edgex-device-opc-ua
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - data
      - command

  device-bacnet-ip:
    image: docker.iotechsys.com/edgexpert/device-bacnet-ip-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /device-bacnet-c/build/release/device-bacnet-c
      - --confdir=/device-bacnet-c/res
      - --name=device-bacnet-ip
      - --registry=${EX_CONSUL}
    ports:
      - "49901:49901"
    container_name: edgex-device-bacnet-ip
    hostname: edgex-device-bacnet-ip
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - metadata
      - data
      - command
#    environment:
#      - BACNET_BBMD_ADDRESS=$BBMD_ADDRESS
#      - BACNET_BBMD_PORT=$BBMD_PORT

  device-bacnet-mstp:
    image: docker.iotechsys.com/edgexpert/device-bacnet-mstp-${EX_ARCH}:${EX_VER}
    entrypoint:
    - /device-bacnet-c/build/release/device-bacnet-c
    - --confdir=/device-bacnet-c/res
    - --name=device-bacnet-mtsp
    - --registry=${EX_CONSUL}
    ports:
      - "49902:49902"
    container_name: edgex-device-bacnet-mstp
    hostname: edgex-device-bacnet-mstp
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - metadata
      - data
      - command
#    devices:
#      - /dev/ttyUSB0

  device-random:
    image: docker.iotechsys.com/edgexpert/device-random-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /device-random
      - --profile=docker
      - --confdir=/res
      - --registry=${EX_CONSUL}
    ports:
      - "49988:49988"
    container_name: edgex-device-random
    hostname: edgex-device-random
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - metadata
      - data
      - command
#    environment:
#      - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/

  device-modbus:
    image: docker.iotechsys.com/edgexpert/device-modbus-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /device-modbus
      - --profile=docker
      - --confdir=/res
      - --registry=${EX_CONSUL}
    ports:
      - "49991:49991"
    container_name: edgex-device-modbus
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    privileged: true
    depends_on:
      - data
      - command

  device-mqtt:
    image: docker.iotechsys.com/edgexpert/device-mqtt-go-${EX_ARCH}:${EX_VER}
    entrypoint:
      - /device-mqtt
      - --profile=docker
      - --confdir=/res
      - --registry=${EX_CONSUL}
    ports:
      - "49982:49982"
    container_name: edgex-device-mqtt
    hostname: edgex-device-mqtt
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - ./edgexpertLicense:/edgexpert/licenses
    depends_on:
      - data
      - command
    environment:
      - INCOMING_MQTT_BROKER=172.17.0.1
      - INCOMING_MQTT_BROKER_PORT=1883
      - RESPONSE_MQTT_BROKER=172.17.0.1
      - RESPONSE_MQTT_BROKER_PORT=1883

  device-grove:
    image: docker.iotechsys.com/edgexpert/device-grove-${EX_ARCH}:${EX_VER}
    entrypoint:
    - /device-grove
    - --confdir=/res
    - --name=device-grove
    - --registry=${EX_CONSUL}
    ports:
      - "49992:49992"
    devices:
#     - /dev/i2c-5 # for UP Squared (x86, 64-bit)
      - /dev/i2c-1 # for Raspberry Pi (arm 32, 64-bit)
    container_name: edgex-device-grove
    hostname: edgex-device-grove
    networks:
      - edgex-network
    volumes:
      - log-data:/edgex/logs
    depends_on:
      - metadata
      - data
      - command
     
#################################################################
# Tools
#################################################################
  bacnet-server:
    image: docker.iotechsys.com/edgexpert/docker-bacnet-server-${EX_ARCH}:${EX_VER}
    container_name: bacnet-server
    hostname: bacnet-server
    networks:
      - edgex-network
    depends_on:
      - device-bacnet-ip
      
networks:
  edgex-network:
    driver: "bridge"
...
